CC = gcc
CFLAGS = -Wall -Wextra -std=c99

all: serveurV2 addServeur subServeur 
# mulServeur divServeur divEServeur

serveurV2: serveurV2.c
	$(CC) $(CFLAGS) -o serveurV2 serveurV2.c

addServeur: addServeur.c
	$(CC) $(CFLAGS) -o addServeur addServeur.c

subServeur: subServeur.c
	$(CC) $(CFLAGS) -o subServeur subServeur.c

# mulServeur: mulServeur.c
# 	$(CC) $(CFLAGS) -o mulServeur mulServeur.c

# divServeur: divServeur.c
# 	$(CC) $(CFLAGS) -o divServeur divServeur.c

# divEServeur: divEServeur.c
# 	$(CC) $(CFLAGS) -o divEServeur divEServeur.c

# clean:
# rm -f addServeur subServeur 
# mulServeur divServeur divEServeur
